### ISSUE TITLE
Getting Invalid authentication

### ISSUE THREAD

**Issue by Eclipse4Ever** [PTST/G4S-HomeAssistant#14]
Hi,
I am getting the "Invalid authentication" when trying to add the integration (login to G4S).
![image](https://github.com/user-attachments/assets/6378bfe7-c3ef-4561-afca-82da5d1819e2)

The G4S app I have on the phone is called "SHIELDalarm" and has the G4S logo.

**Comment by Eclipse4Ever** [comment]
![image](https://github.com/user-attachments/assets/3c2250c0-cacb-4304-ba12-55f7f1e1cee4)

**Comment by PTST** [comment]
This integration unfortunately only supports their old "smart alarm" system

![image](https://github.com/user-attachments/assets/6d7ddd69-4c4b-4487-b037-b13f80df044e)
