### ISSUE TITLE
I'm not getting authenticated

### ISSUE THREAD

**Issue by Distenze** [PTST/G4S-HomeAssistant#2]
Hi, 

When i input my details and pressing submit, I'm getting an "invalid Authentication".
I have double checked both mail and password.

I have only just installed the integration, I'm unaware if any post installation tasks is needed.

**Comment by PTST** [comment]
Hi

Which app do you use on your phone normally? This only works with systems using the G4SSMARTalarm app

**Comment by AMajland** [comment]
abd the g4s everhome alarm app (just the other one branded differently)
