### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by PGLDK** [PTST/G4S-HomeAssistant#4]
No problem in connecting, but gets the error: Trying communication again, list index out of range.

**Comment by PGLDK** [comment]
Unexpected error fetching g4s_alarm data: list index out of range
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/g4s_alarm/coordinator.py", line 64, in _async_update_data
    "panel": [device for device in self.alarm.sensors if device.type == DeviceType.PANEL][0]
IndexError: list index out of range

**Comment by RonniHolst** [comment]
I am having the same issue here ...

Logger: custom_components.g4s_alarm
Source: custom_components/g4s_alarm/coordinator.py:64
Integration: G4S ([documentation](https://github.com/PTST/G4S-HomeAssistant), [issues](https://github.com/PTST/G4S-HomeAssistant/issues))
First occurred: 5:05:48 PM (78 occurrences)
Last logged: 6:44:14 PM

Unexpected error fetching g4s_alarm data: list index out of range
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 191, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/g4s_alarm/coordinator.py", line 64, in _async_update_data
    "panel": [device for device in self.alarm.sensors if device.type == DeviceType.PANEL][0]
IndexError: list index out of range

Any help?

**Comment by ThomasEg** [comment]
Me too...albeit a bit different callstack:
Logger: custom_components.g4s_alarm
Source: custom_components/g4s_alarm/coordinator.py:64
Integration: G4S ([documentation](https://github.com/PTST/G4S-HomeAssistant), [issues](https://github.com/PTST/G4S-HomeAssistant/issues))
First occurred: 17:50:55 (5 occurrences)
Last logged: 17:52:13

Unexpected error fetching g4s_alarm data: list index out of range
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/g4s_alarm/coordinator.py", line 64, in _async_update_data
    "panel": [device for device in self.alarm.sensors if device.type == DeviceType.PANEL][0]
IndexError: list index out of range

**Comment by ThomasEg** [comment]
... if anyone else gets stuck on this issue, i've found a workaround: I just deleted line 64 in "/config/custom_components/g4s_alarm/coordinator.py" using Visual Studio Code....had to restart HA and re-add the integration, but then it worked :-)

Edit: I found out i kinda needed the panel, so instead i've changed line 64 to this:
```
            "panel": {
                device.name: device
                for device in self.alarm.sensors if device.type == DeviceType.PANEL
            },
```

Besides this, there is something "fishy" with the battery-stuff in "alarm_control_panel.py" on line 108. I had to remove line 108, 109 and 111. Basically voiding the function.

**Comment by luckow** [comment]
Brilliant, that worked for me @ThomasEg

**Comment by PTST** [comment]
I have deployed a beta release that seems to fix this issue, if any of you could try it out before i deploy to prod, it would be great

It can be downloaded by going to HACS, finding the G4S Alarm integration. then clicking on the 3 dots in the top right corner. Clicking redownload. Then enable Show beta versions.

Then you can select version 0.2.2-beta.2 as the version. and then click download and restart HA

![image](https://user-images.githubusercontent.com/17211264/192955667-f158f31a-3de9-4b7c-bbf7-e65c25bd6e1d.png)

**Comment by luckow** [comment]
@PTST it works for me. I haven't tried deleting and reinstalling, but I have updated to the beta version, and I see no errors now. I even got a status on the alarm itself, it was unavailable until I updated.
<img width="1200" alt="Skærmbillede 2022-09-29 kl  22 45 05" src="https://user-images.githubusercontent.com/85778/193138496-783f3ec2-34f3-4f92-a72e-302b391abb22.png">

**Comment by hausner** [comment]
> I have deployed a beta release that seems to fix this issue, if any of you could try it out before i deploy to prod, it would be great
> 
> It can be downloaded by going to HACS, finding the G4S Alarm integration. then clicking on the 3 dots in the top right corner. Clicking redownload. Then enable Show beta versions.
> 
> Then you can select version 0.2.2-beta.2 as the version. and then click download and restart HA
> 
> ![image](https://user-images.githubusercontent.com/17211264/192955667-f158f31a-3de9-4b7c-bbf7-e65c25bd6e1d.png)

 Beta fixed it here

**Comment by AMajland** [comment]
Beta fixed it here as well
