### ISSUE TITLE
Account type

### ISSUE THREAD

**Issue by KTHconsult** [PTST/G4S-HomeAssistant#5]
Hi,

Im also having issues authenticating. I suspect my account to be the problem though. I have the SHIELDAlarm account. Do you expect this to work with that account type?
If not, maybe that could be your next integration project ;-)

Kjeld-

**Comment by luckow** [comment]
It works on my old G4S Everhome system

**Comment by PTST** [comment]
This onlu works with the G4SSMARTa larm system. I unfortunately don't  have access to any of their other systems so I can't develop for them
