### ISSUE TITLE
Cant disarm from Home Assistant

### ISSUE THREAD

**Issue by hausner** [PTST/G4S-HomeAssistant#6]
I can enable arm and night_arm but any attempt to disarm does not work

Service call from Home Assistant is pretty basic:

service: alarm_control_panel.alarm_disarm
data:
  code: "XXXX"
target:
  entity_id: alarm_control_panel.g4s_alarm

I have tried:
* double and triple checked the password. 
* Changed tag passcode in G4S and adjusted the service call in Home Assistant
* created a tag without a passcode in G4S and run the service from HA without a passcode. 
* running the service without "" around code value
* disarming from the little numpad on the entity.

No warning or error is thrown and Log is empty. even with debugging enabled from the integration.
I even get the little checkmark on the button when clicking "run service" in the HA "Services" menu. 
But the alarm is never disarmed. 

Im running the beta version that fixed this issue: https://github.com/PTST/G4S-HomeAssistant/issues/4

I will be happy to provide additional info.

**Comment by hausner** [comment]
Im not sure what is wrong with the Home Assistant integration in my situation, but i took the liberty to look into the code and was able to fire a post request from Postman to G4S servers that actually disarmed the alarm. But i never used the pin code. I used the PanelID the state info (systemstatus/getState).
![image](https://user-images.githubusercontent.com/2352961/215296560-bc40739d-e119-4b4b-b253-cb96784bbda0.png)

**Comment by PTST** [comment]
Hi @hausner

The API does not actually need the pin to disarm it. 
What happens in the code is that we get a list of all users and their pins and then check locally whether that pin is matching a known user pin before allowing sending of the disarm request.

Are you sure that a pin is actually set for the user?

If you in postman makes a post request to 
```
https://mit.g4severhome.dk/ESI.API/API/systemstatus/getState
```
with the body 

```JSON
{
	"panelId": "{{ panel_id }}",
	"username": "{{ username }}",
	"password": "{{ password }}"
}
```

then in the received object you nedd to go the "users" property and check that one of the users in the array has a property called accessCode with the pin you used in home assistant set

**Comment by hausner** [comment]
hmm. The accesscode under all user properties are set to null.
The only place the accesscode is set is under "stateDevices".  So for example on a device named "Martins chip"

**Comment by PTST** [comment]
Are you able to disarm your alarm without using the chip? So by just entering your passcode on the alarm panel?

**Comment by PTST** [comment]
My user settings are set like this in the app. But be warned that this will alter you settings to allow disarm without a chip

![image](https://user-images.githubusercontent.com/17211264/218396814-edb80fa5-3358-4fa4-80e0-fe0345ada75d.jpeg)

![image](https://user-images.githubusercontent.com/17211264/218396832-a37dacf7-4202-4eec-9e45-ead167df35c4.jpeg)

![image](https://user-images.githubusercontent.com/17211264/218396862-6ff67b05-3020-4504-a5a4-505cd4f50fc0.jpeg)

**Comment by hausner** [comment]
hmm. i only have the "Chips" section, no "Bruger adgangskode".
Any idea how to add that?

**Comment by PTST** [comment]
Unfortunately not. But i'm just now testing a new version that also checks the chip access codes. It should be ready for release later today.

**Comment by PTST** [comment]
Please try upgrading to v0.2.4, this version should fix your issue

**Comment by hausner** [comment]
Sorry for the delay. 
Tried the 0.2.4 with no luck though. Still cant disarm from HA.
I see that i have a chip in "stateDevices" with "Type": 201 which i guess should match the DeviceType.ACCESSCHIP (could find it in the code to check though).
That state device has the "accessCode":  value set to the correct pin that im using in HA. But still no luck

snippet:
             "accessCode": "xxxx",
            "key": null,
            "isTampered": null,
            "hasLowBattery": null,
            "hasSupervisionFault": null,
            "Id": 4,
            "Type": 201,
            "Name": "Tag-4",
            "ParentDeviceId": null,
            "PanelId": 10004608

**Comment by PTST** [comment]
There seemed to be a parsing error in the underlying api library.
I have fixed it and released a new version of the integration, please try the 0.2.5 version just release

**Comment by hausner** [comment]
yeah, works now. 
Thanks a lot. Really appreaciate it
