### ISSUE TITLE
Polling frequency of temperature sensors

### ISSUE THREAD

**Issue by tobiasnorbo** [PTST/G4S-HomeAssistant#9]
Hi,

I am wondering how I could change the polling frequency of the temperature sensors? I know I need to do it through an automation, but I don't know what I should put in to ensure it works correctly.

My intention is to use the sensors to create automations if a fire occur, but at the moment it looks like they are updated so seldomly, that it wouldn't make sense.

I want to use these sensors, as they are placed in positions, where they would quickly detect an increase in temperature during a fire, and since they are with batteries they would be less affected of partial power outage. 

Hope you can help :)

**Comment by PTST** [comment]
It's not possible to change the polling interval for just temperature sensors.  
But we could make the polling interval configurable and then it would update all the entities with this interval.  
Do note though that Home Assistant does not support a higher frequency than every 5 seconds. And i do not know how performance would be impacted by doing this to frequently, or if we would hit any rate limits on the G4S API if we hit it this often.  

But i believe that configurability is a good thing. So i will look into when i have the time 🙂

**Comment by PTST** [comment]
@tobiasnorbo I have added this as a setting in v0.2.8. Please update and let me know if this works 🙂 

You can access the settings here:   
[![Open your Home Assistant instance and show an integration.](https://my.home-assistant.io/badges/integration.svg)](https://my.home-assistant.io/redirect/integration/?domain=g4s_alarm)

**Comment by tobiasnorbo** [comment]
That was quick! 

The configuration itself works. I changed polling to 10s, but so far I have not seen 10s between datapoints. Also it seems that the sensor granularity is 1 whole degree C change. I just hope it reacts fast enough in case of a fire.

To test it I have opened a door (3 degrees C outside), where the sensor is placed to see how the temperature drops. For now it is not fast at all. The door has been open for 20 minutes and only dropped one degree on the door open/close sensor after 10 minutes and 1 deg. C drop for the Alarm speaker close to the ceiling, at the door.

In the meantime the room sensor (not G4S) 3m away from the open door had dropped 5 deg. C. this one unfortunately not in HA

Maybe this use case simply doesn't work.

**Comment by PTST** [comment]
Do you see the changes faster in the official app? If not I'm guessing they just don't update that often, they are after all battery powered.  
If that is the case then polling more often won't change anything and there is nothing to do about it.

The api only returns the temperature as whole numbers. Unfortunately I also cannot do anything about that
